## Demonstration Of Extrinsic and Intrinsic Rotations

To completely define a Euler angle system, one must choose from among the following possible permutations: 
  Tait-Bryan vs. Classic,
  Rotation order,
  Intrinsic vs. Extrinsic rotations,
  Active vs. Passive rotations,
  Coordinate system conventions

 The common convention is Tait-Bryan Euler angle convention using active, intrinsic rotations around the axes in the order z-y-x. We will call the rotation angles yaw, pitch and roll respectively. 

 Intrinsic vs. Extrinsic rotations: In an intrinsic system, each of the elemental rotations is performed on the coordinate system as rotated by the previous operation(s). In an extrinsic system, each rotation is performed around the axes of the world coordinate system, which does not move. 

Source: https://danceswithcode.net/engineeringnotes/rotations_in_3d/rotations_in_3d_part1.html

In [ ]:
%pip install -q pyquaternion
%pip install -q numpy

In [ ]:
from pyquaternion import Quaternion

In [3]:
import numpy as np

In [ ]:
# Define the rotations along cartesian coordinate axes
rotx, roty, rotz = np.pi/2, -np.pi/2, np.pi  # 90, -90, 180 deg rotations about x,y,z

In [ ]:
qx = Quaternion(axis=[1, 0, 0], angle=rotx)    # Defines a rotation about x axis
qy = Quaternion(axis=[0, 1, 0], angle=roty)    # Defines a rotation about y axis
qz = Quaternion(axis=[0, 0, 1], angle=rotz)    # Defines a rotation about z axis

### Create intrinsic rotation quaternion by combining the three rotations. Each multiplication is done on previous quaternion(orientation), hence this represents and intrinsic transformation

In [ ]:
# Intrinsic ZYX
q_int_zyx = qz*qy*qx
q_int_zyx

Quaternion(-0.49999999999999983, 0.5, 0.49999999999999994, 0.5000000000000001)

In [ ]:
# Intrinsic XYZ
q_int_xyz = qx*qy*qz
q_int_xyz

Quaternion(0.49999999999999994, -0.49999999999999994, -0.5, 0.5000000000000001)

### Rotate a point v0 using Extrinsic and Intrinsic Rotations

In [ ]:
v0 = np.array([3, 4., 5.])

In [ ]:
# Intrinsic zyx
v1_int_zyx = q_int_zyx.rotate(v0)
v1_int_zyx

array([4., 5., 3.])

In [ ]:
# Extrinsic XYZ
v_temp1 = qx.rotate(v0)
v_temp2 = qy.rotate(v_temp1)  # qy is a rotation in original frame of reference. Hence this is extrinsic.
v1_ext_xyz = qz.rotate(v_temp2)  # qx is also a rotation in original frame of reference. Hence this is extrinsic.
v1_ext_xyz

array([4., 5., 3.])

In [ ]:
# Intrinsic xyz
v1_int_xyz = q_int_xyz.rotate(v0)
v1_int_xyz

array([-5.,  3., -4.])

In [ ]:
# Extrinsic YZX
v_temp1 = qz.rotate(v0)
v_temp2 = qy.rotate(v_temp1)
v1_ext_zyx = qx.rotate(v_temp2)
v1_ext_zyx

array([-5.,  3., -4.])

### We can see that new pooint v1 is same for intrinsic ZYX and Extrinsic XYZ. 
### Hence doing extrinsic rotations in order XYZ is same as intrinsic rotations in order ZYX. Similarly intrinsic XYZ is same as extrinsic ZYX.